spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academia?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        implicity-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  packagesToScan: com.academia.securizacion.controller
  pathsToMatch: /**
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
